apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-uvcj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-uvcj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-uvcj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-uvcj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-uvcj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jwaq-tenant/rhtap-demo-app/hacbs-test-project-uvcj@sha256:0e57d88c6b06ae1c1bc4b51fcfbeeeed53dd33d698dafd99853ce0c5ea880323
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
